#!/bin/bash

# This script will find .rar files recursively and extract the files in their directories.
# After the succesful unrar the function 'findremove()' will delete all .rar files.

if [ -z $1 ] ; then
  echo "usage: auto_extract.sh /full/path/to/directory &> /dev/null &"
  exit
fi

parent=$1
path=""

if [ ! -z $2 ] ; then
  path=$2
fi

email="youremail@domain.com"

findremove() {
	 echo "Wanted to remove"
#        find $(pwd) -regextype posix-egrep -iregex '^.*\.r([0-9]+|ar)$' -exec echo "Wanted to remove:" {} \;
}

find $parent -iname '*.rar' | while read file
do
        d=$(dirname "$file")
        f=$(basename "$file")
        # only unrar part01.rar and rars

        if echo $f | grep -q 'part[0-9]*.rar$'; then
            if ! echo $f | grep -q 'part01.rar$'; then
                continue
            fi
        fi
        cd "$d"

        echo "Extracting $f"

        if unrar x -o+ "$f" "$path"; then
           findremove
        else
           mail -s "unRAR ERROR" $email <<< "Extract failed within directory: $d"
        fi
        cd "$parent"
done
